"""Generate hook scripts for Claude Code, shell, and git."""

from __future__ import annotations

import sys
from pathlib import Path

_PRE_HOOK_TEMPLATE = """#!/usr/bin/env bash
# kibitzer PreToolUse hook — path guard + interceptors
# Generated by: kibitzer init
exec {python} -m kibitzer.hooks.pre_tool_use
"""

_POST_HOOK_TEMPLATE = """#!/usr/bin/env bash
# kibitzer PostToolUse hook — mode controller + coach
# Generated by: kibitzer init
exec {python} -m kibitzer.hooks.post_tool_use
"""

_GIT_PRE_COMMIT_TEMPLATE = """#!/usr/bin/env bash
# kibitzer pre-commit guard — validates staged files against mode writable paths
# Generated by: kibitzer init --git-hooks
{python} -m kibitzer validate-staged
"""

_SHELL_INTEGRATION = r"""
# kibitzer shell integration — add to .bashrc or .zshrc
# Shows current mode in prompt, coaches shell commands

_kibitzer_prompt() {
    local state_file=".kibitzer/state.json"
    if [[ -f "$state_file" ]]; then
        local mode fails
        eval "$(python3 -c "
import json, sys
try:
    d = json.load(open('$state_file'))
    m = str(d.get('mode', '')).replace(\"'\", '')
    f = int(d.get('consecutive_failures', 0))
    print(f\"mode='{m}' fails={f}\")
except Exception:
    print(\"mode='' fails=0\")
" 2>/dev/null)"
        mode=${mode//[^a-zA-Z0-9_-]/}
        if [[ -n "$mode" ]]; then
            local indicator="$mode"
            if [[ "$fails" -ge 3 ]]; then
                indicator="${mode}!"
            fi
            printf '[kib:%s]' "$indicator"
        fi
    fi
}

# For bash: PS1='$(_kibitzer_prompt) \$ '
# For zsh:  PROMPT='$(_kibitzer_prompt) %# '

_kibitzer_preexec() {
    local cmd="$1"
    case "$cmd" in
        git\ add*|git\ commit*|git\ push*|git\ checkout*|git\ reset*|\
        pytest*|python\ -m\ pytest*)
            kibitzer shell-post "$cmd" 2>/dev/null
            ;;
    esac
}

# For bash (requires bash-preexec): preexec_functions+=(_kibitzer_preexec)
# For zsh: preexec_functions+=(_kibitzer_preexec)
""".lstrip()


def write_hook_scripts(hooks_dir: Path) -> tuple[Path, Path]:
    """Write bash hook scripts using the python that ran kibitzer init."""
    hooks_dir.mkdir(parents=True, exist_ok=True)
    python = sys.executable

    pre_path = hooks_dir / "kibitzer-pre.sh"
    pre_path.write_text(_PRE_HOOK_TEMPLATE.format(python=python))
    pre_path.chmod(0o755)

    post_path = hooks_dir / "kibitzer-post.sh"
    post_path.write_text(_POST_HOOK_TEMPLATE.format(python=python))
    post_path.chmod(0o755)

    return pre_path, post_path


def write_git_pre_commit_hook(project_dir: Path) -> Path:
    """Write a git pre-commit hook that validates staged files."""
    git_hooks_dir = project_dir / ".git" / "hooks"
    if not git_hooks_dir.exists():
        git_hooks_dir.mkdir(parents=True, exist_ok=True)

    hook_path = git_hooks_dir / "pre-commit"
    python = sys.executable

    if hook_path.exists():
        existing = hook_path.read_text()
        if "kibitzer" not in existing:
            with open(hook_path, "a") as f:
                f.write(
                    f"\n# kibitzer pre-commit guard\n"
                    f"{python} -m kibitzer validate-staged\n"
                )
    else:
        hook_path.write_text(_GIT_PRE_COMMIT_TEMPLATE.format(python=python))

    hook_path.chmod(0o755)
    return hook_path


def shell_integration_snippet() -> str:
    """Return the shell integration snippet for sourcing."""
    return _SHELL_INTEGRATION
