"""Generate bash hook scripts for .claude/hooks/."""

from __future__ import annotations

import sys
from pathlib import Path

_PRE_HOOK_TEMPLATE = """#!/usr/bin/env bash
# kibitzer PreToolUse hook — path guard + interceptors
# Generated by: kibitzer init
exec {python} -m kibitzer.hooks.pre_tool_use
"""

_POST_HOOK_TEMPLATE = """#!/usr/bin/env bash
# kibitzer PostToolUse hook — mode controller + coach
# Generated by: kibitzer init
exec {python} -m kibitzer.hooks.post_tool_use
"""


def write_hook_scripts(hooks_dir: Path) -> tuple[Path, Path]:
    """Write bash hook scripts using the python that ran kibitzer init."""
    hooks_dir.mkdir(parents=True, exist_ok=True)
    python = sys.executable

    pre_path = hooks_dir / "kibitzer-pre.sh"
    pre_path.write_text(_PRE_HOOK_TEMPLATE.format(python=python))
    pre_path.chmod(0o755)

    post_path = hooks_dir / "kibitzer-post.sh"
    post_path.write_text(_POST_HOOK_TEMPLATE.format(python=python))
    post_path.chmod(0o755)

    return pre_path, post_path
